---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm

workspace:
  base: /go
  path: src/github.com/drone/drone-vault
steps:
- name: build
  image: golang:1.10
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go build -v -a -tags netgo -o release/linux/arm/drone-vault github.com/drone/drone-vault/cmd/drone-vault
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: ikaruswill/drone-vault
    username:
      from_secret: docker_username
